from pydantic import BaseModel, EmailStr, Field, constr
from typing import Optional

class SignUp(BaseModel):
    """
    Contract for creating a new Multi-Tenant Identity.
    Enforces strict password complexity.
    """
    email: EmailStr = Field(..., description="The user's email address.")
    password: constr(min_length=12, max_length=128) = Field(
        ..., 
        description="At least 12 characters required by VTE Tier 1 standards."
    )
    full_name: str = Field(..., min_length=2, max_length=100)
    tenant_id: str = Field(..., description="The workspace this user belongs to.")


class SignIn(BaseModel):
    """
    Contract for authenticating an existing Identity.
    """
    email: EmailStr
    password: str


class MFAChallenge(BaseModel):
    """
    Contract generated by the server when a SignIn requires TOTP verification.
    """
    mfa_token_id: str = Field(..., description="Temporary token claiming the pre-auth session.")
    challenge_type: str = Field(default="TOTP")


class MFAVerify(BaseModel):
    """
    Contract for submitting the Time-Based One-Time Password.
    """
    mfa_token_id: str
    totp_code: constr(min_length=6, max_length=6) = Field(..., description="The 6-digit authenticator code.")
