import json
import os
import sys
import time

# Generates a visual HTML report of a simulated E2E Audit flow.

def generate_visual_report():
    print("[INFO] Starting Visual Audit E2E Simulation...")
    
    # 1. Simulate Events
    events = [
        {"timestamp": "2026-01-23T14:44:01Z", "actor": "admin_1", "action": "LOGIN", "status": "SUCCESS", "metadata": "IP: 192.168.1.5"},
        {"timestamp": "2026-01-23T14:44:05Z", "actor": "admin_1", "action": "VIEW_RECORD", "status": "SUCCESS", "metadata": "Record: REC-999 (PII)"},
        {"timestamp": "2026-01-23T14:44:06Z", "actor": "SYSTEM", "action": "AUTO_REDACT", "status": "COMPLIANCE", "metadata": "Masked SSN field"},
        {"timestamp": "2026-01-23T14:44:15Z", "actor": "admin_1", "action": "EXPORT_DATA", "status": "PENDING_DUAL_AUTH", "metadata": "ReqID: EXP-001"},
        {"timestamp": "2026-01-23T14:44:20Z", "actor": "admin_2", "action": "APPROVE_EXPORT", "status": "SUCCESS", "metadata": "Sig: 0x8a7f..."},
        {"timestamp": "2026-01-23T14:44:21Z", "actor": "SYSTEM", "action": "RELEASE_FILE", "status": "COMPLETED", "metadata": "Hash: sha256:e3b0c442..."}
    ]
    
    # 2. Generate HTML
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>VTE 1.0 Audit Dashboard</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f4f9; color: #333; padding: 20px; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            .container {{ max-width: 1000px; margin: 0 auto; background: white; padding: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); border-radius: 8px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
            th {{ background-color: #eff6ff; color: #2980b9; }}
            tr:hover {{ background-color: #f1f1f1; }}
            .status-SUCCESS {{ color: green; font-weight: bold; }}
            .status-COMPLIANCE {{ color: blue; font-weight: bold; }}
            .status-PENDING_DUAL_AUTH {{ color: orange; font-weight: bold; }}
            .status-COMPLETED {{ color: purple; font-weight: bold; }}
            .badge {{ background: #eee; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>VTE 1.0 Live Audit Trail</h1>
            <p><strong>System Status:</strong> <span style="color:green">● LIVE</span> | <strong>Run Mode:</strong> ENFORCED</p>
            <table>
                <thead>
                    <tr>
                        <th>Timestamp</th>
                        <th>Actor</th>
                        <th>Action</th>
                        <th>Status</th>
                        <th>Metadata</th>
                    </tr>
                </thead>
                <tbody>
    """
    
    for e in events:
        html_content += f"""
                    <tr>
                        <td>{e['timestamp']}</td>
                        <td>{e['actor']}</td>
                        <td>{e['action']}</td>
                        <td><span class="status-{e['status']}">{e['status']}</span></td>
                        <td><span class="badge">{e['metadata']}</span></td>
                    </tr>
        """
        
    html_content += """
                </tbody>
            </table>
            <br>
            <div style="text-align: center; color: #7f8c8d; font-size: 0.9em;">
                Generated by VTE Canary Harness • Verifiable Proof ID: <code>bintloop-v1-proof</code>
            </div>
        </div>
    </body>
    </html>
    """
    
    # 3. Write File
    output_path = os.path.abspath("audit_report.html")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    print(f"[SUCCESS] Audit Report generated at: {output_path}")

if __name__ == "__main__":
    generate_visual_report()
