"""Initial Schema

Revision ID: 8e58b21da540
Revises: 
Create Date: 2026-02-03 23:00:40.249864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e58b21da540'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_bundles',
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('normalization_schema', sa.String(), nullable=False),
    sa.Column('items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bundle_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bundle_id'),
    sa.UniqueConstraint('bundle_hash')
    )
    op.create_table('decision_objects',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('actor_role', postgresql.ENUM('super_admin', 'admin', 'user', 'auditor', 'system_bot', name='role_enum'), nullable=False),
    sa.Column('actor_session_id', sa.String(), nullable=True),
    sa.Column('intent_action', sa.String(), nullable=False),
    sa.Column('intent_target', sa.String(), nullable=False),
    sa.Column('intent_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_hash', sa.String(), nullable=True),
    sa.Column('outcome', postgresql.ENUM('APPROVED', 'DENIED', 'NEEDS_MORE_EVIDENCE', name='outcome_enum'), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('permit_token_id', sa.UUID(), nullable=True),
    sa.Column('decision_hash', sa.String(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_hash'], ['evidence_bundles.bundle_hash'], ),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('decision_hash')
    )
    op.create_table('permit_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('scope_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_objects.decision_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('decision_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permit_tokens')
    op.drop_table('decision_objects')
    op.drop_table('evidence_bundles')
    # ### end Alembic commands ###
